import React from "react";
import { StyleProp, ViewStyle, TextStyle } from "react-native";
import { ConnectionState } from "../types";
export interface OrgaAIControlsProps {
    connectionState: ConnectionState;
    isCameraOn: boolean;
    isMicOn: boolean;
    onStartSession: () => void;
    onEndSession: () => void;
    onToggleCamera: () => void;
    onToggleMic: () => void;
    onFlipCamera: () => void;
    containerStyle?: StyleProp<ViewStyle>;
    controlsOverlayStyle?: StyleProp<ViewStyle>;
    controlButtonStyle?: StyleProp<ViewStyle>;
    controlLabelStyle?: StyleProp<TextStyle>;
    connectButtonStyle?: StyleProp<ViewStyle>;
    disconnectButtonStyle?: StyleProp<ViewStyle>;
    cameraOnIcon?: React.ReactNode;
    cameraOffIcon?: React.ReactNode;
    micOnIcon?: React.ReactNode;
    micOffIcon?: React.ReactNode;
    flipIcon?: React.ReactNode;
    endIcon?: React.ReactNode;
    startIcon?: React.ReactNode;
    startButtonText?: string;
    connectingText?: string;
    disconnectText?: string;
    cameraOnText?: string;
    cameraOffText?: string;
    micOnText?: string;
    micOffText?: string;
    flipText?: string;
    endText?: string;
    connectSubtext?: string;
    showCameraControl?: boolean;
    showMicControl?: boolean;
    showFlipCameraControl?: boolean;
    showEndSessionControl?: boolean;
    loadingIndicator?: React.ReactNode;
    loadingIndicatorColor?: string;
}
export declare const OrgaAIControls: ({ connectionState, isCameraOn, isMicOn, onStartSession, onEndSession, onToggleCamera, onToggleMic, onFlipCamera, containerStyle, controlsOverlayStyle, controlButtonStyle, controlLabelStyle, connectButtonStyle, disconnectButtonStyle, cameraOnIcon, cameraOffIcon, micOnIcon, micOffIcon, flipIcon, endIcon, startIcon, startButtonText, connectingText, disconnectText, cameraOnText, cameraOffText, micOnText, micOffText, flipText, endText, connectSubtext, showCameraControl, showMicControl, showFlipCameraControl, showEndSessionControl, loadingIndicator, loadingIndicatorColor, }: OrgaAIControlsProps) => React.JSX.Element;
